version: "3.9"

services:
  frontend:
    build:
      context: ../../apps/frontend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ../../apps/frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: pnpm dev
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ../../apps/backend:/app
      - ../../packages/types:/app/node_modules/@types/shared
      - /app/node_modules
    ports:
      - "5000:5000"
    command: pnpm start:dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
